### ISSUE TITLE
How to programmatically trigger "Next" or "Finish"?

### ISSUE THREAD

**Issue by creswick** [cjwizard/cjwizard#11]
_From [thilopl...@googlemail.com](https://code.google.com/u/117235970602675925417/) on March 24, 2013 23:00:10_

I have a screen with a couple of JToggleButton that decide what the next step will be. Instead of pressing one of them and then "Next", I'd like to go to the next page directly when those buttons have been clicked.

How can I programmatically trigger "Next" or "Finish"? Issue #9 might be related.

_Original issue: http://code.google.com/p/cjwizard/issues/detail?id=11_

**Comment by Petikoch** [comment]
Closed because no updates on this issue since 2014. Please reopen if necessary.
