### ISSUE TITLE
No easy way to update the page title without changing WizardPages.

### ISSUE THREAD

**Issue by creswick** [cjwizard/cjwizard#2]
_From [cresw...@gmail.com](https://code.google.com/u/104677812953833386554/) on July 14, 2008 09:56:55_

The WizardController API doesn't expose any means of changing the page
title as displayed in the PageTemplate, or on any surrounding "chrome" (for
example, on the dialog window border.)

One solution is to add a `titleChanged(String newTitle)` event to the
!WizardListener interface, and a `setTitle(String title)` method on the
!WizardController.  I think that this method would then be fired before or
after the `pageChanged(...)` listener event, but I'm not sure which --
probably after, so the UI changes take effect later than any
post-processing of the !WizardPage and !WizardSettings that the associated
!WizardListeners need to perform.

_Original issue: http://code.google.com/p/cjwizard/issues/detail?id=2_

**Comment by Petikoch** [comment]
Closed because no updates on this issue since 2014. Please reopen if necessary.
