### ISSUE TITLE
Dependency on Apache Commons Logging

### ISSUE THREAD

**Issue by creswick** [cjwizard/cjwizard#3]
_From [Kissa...@gmail.com](https://code.google.com/u/106643232835441602005/) on November 16, 2010 03:01:30_

cjwizard depends on org.apache.commons.logging.LogFactory which is pretty bad for a wizard library which could otherwise be used in a variety of projects not using apache commons logging.

Thus, logging should be dropped (it’s debug only anyway) or made optional.

_Original issue: http://code.google.com/p/cjwizard/issues/detail?id=3_

**Comment by Petikoch** [comment]
I agree on this one. It's better if a library has no dependencies at all... 

For all Slf4J-Users out there like me... there's an easy workaround to get rid of this issue. Just add `jcl-over-slf4j` explicitly as dependency and remove the `commons-logging` and `log4j` dependencies.

For more details see http://www.slf4j.org/legacy.html.

**Comment by creswick** [comment]
I just tried switching to slf4j.

Since the test suite isn't that comprehensive, and I don't actually use this project any more it's difficult for me to tell if I actually solved the problem.

Could one of you folks take a look? The work is on this branch: 

https://github.com/cjwizard/cjwizard/tree/feature/slf4j

Thanks!

**Comment by Petikoch** [comment]
@creswick  

https://github.com/cjwizard/cjwizard/tree/feature/slf4j looks good!

+1
