### ISSUE TITLE
Unespecified version for plugin maven-source-plugin in the pom.xml

### ISSUE THREAD

**Issue by PhoneixS** [cjwizard/cjwizard#33]
The Travis CI have a warning (show bellow) telling that we haven't specified the version of maven-source-plugin. What version we used so we can fix it?

```
[WARNING]

[WARNING] Some problems were encountered while building the effective model for com.github.cjwizard:cjwizard:jar:1.0.0

[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 64, column 15

[WARNING]

[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.

[WARNING]

[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.

[WARNING] 
```

**Comment by guerda** [comment]
Hm, interesting. Yes, Maven uses the source plugin because of the build properties. A added the maven-source-plugin with version into the pom, see branch bug-33. https://github.com/cjwizard/cjwizard/blob/bug-33/ Should build on Travis right now.

**Comment by PhoneixS** [comment]
Can be the version added into the already existing maven-source-plugin?

**Comment by PhoneixS** [comment]
He puesto la version en el plugin que ya teníamos.
