### ISSUE TITLE
First release to sonatype

### ISSUE THREAD

**Issue by PhoneixS** [cjwizard/cjwizard#35]
I think is time to release to the maven repository as the ticket that was opened (https://issues.sonatype.org/browse/OSSRH-14241) was closed as Fixed.

This have to be done by @creswick as I think is who have the rights to do it. You can see how to do it with http://central.sonatype.org/pages/releasing-the-deployment.html.

This is needed to close #14 finally.

**Comment by guerda** [comment]
@creswick Please tell me about the package problems you mentioned in #14. I used in on my pc and it worked fine.

**Comment by creswick** [comment]
@guerda I'm having trouble finding the (2?) maven commands to create the release now (they're in a ticket or PR, but I've lost track of which one).

When I ran those, the first step failed part way through, but it *was* able to tag the release (and pushed that to github...) It failed during some of the signing process because I didn't have that set up locally, and it didn't seem to recover properly, but it was far enough along that I couldn't make progress on either command.

I should try again, if you could post the commands again here.  (Long story -- I had to repave my machine this week, so I'm in a different state, but most things should be restored from backups.)

**Comment by guerda** [comment]
mvn release:prepare prepares the release in that way that the tag is created in SCM and your pom is ready for the next version. If you want to test the preparation without tagging the version in SCM, you can append -DdryRun=true. [More details on mvn release:prepare](https://maven.apache.org/maven-release/maven-release-plugin/prepare-mojo.html)
mvn release:perform then builds the artifact from the created tag and signs it.
If the prepare fails, you can always execute mvn release:rollback to revert the changes in the trunk. The tag cannot be reverted immediately.
I hope your reinstallation went fine. Good luck with the signing. If you have got any question, just drop me a line, you can send me a PM, too.

**Comment by creswick** [comment]
Thanks!  I'm still having issues, though.  It may be easiest to just bump to 1.0.1-SNAPSHOT and release that...

Here's what happens, using master from the github repo:

`mvn release:prepare` fails because no SNAPSHOT version is set.

```
$ mvn release:prepare
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building CJWizard 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-release-plugin:2.3.2:prepare (default-cli) @ cjwizard ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.360 s
[INFO] Finished at: 2015-04-09T08:54:08-07:00
[INFO] Final Memory: 12M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.3.2:prepare (default-cli) on project cjwizard: You don't have a SNAPSHOT project in the reactor projects list. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

`mvn release:rollback` fails because there is no pom.xml.releaseBackup (I don't have the workspace at hand where I started the process, I might be able to get that back if really necessary.)

```
 $ mvn release:rollback
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building CJWizard 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-release-plugin:2.3.2:rollback (default-cli) @ cjwizard ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.373 s
[INFO] Finished at: 2015-04-09T08:54:18-07:00
[INFO] Final Memory: 13M/310M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.3.2:rollback (default-cli) on project cjwizard: Cannot restore from a missing backup POM: /Users/creswick/development/cjwizard/pom.xml.releaseBackup -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

`mvn release:perform` fails because no scm url is specified (maybe because things from the prepare step are missing?)

`mvn release:perform -DconnectionUrl=scm:git:https://github.com/cjwizard/cjwizard/` also fails, but due to a 'checkout failed' issue that seems odd to me (see below).

```
$ mvn release:perform -DconnectionUrl=scm:git:https://github.com/cjwizard/cjwizard/
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building CJWizard 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-release-plugin:2.3.2:perform (default-cli) @ cjwizard ---
[INFO] Checking out the project to perform the release ...
[INFO] Executing: /bin/sh -c cd /Users/creswick/development/cjwizard/target && git clone --branch https://github.com/cjwizard/cjwizard/ /Users/creswick/development/cjwizard/target/checkout
[INFO] Working directory: /Users/creswick/development/cjwizard/target
[ERROR] The git-clone command failed.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.103 s
[INFO] Finished at: 2015-04-09T08:58:32-07:00
[INFO] Final Memory: 13M/310M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.3.2:perform (default-cli) on project cjwizard: Unable to checkout from SCM
[ERROR] Provider message:
[ERROR] The git-clone command failed.
[ERROR] Command output:
[ERROR] fatal: repository '/Users/creswick/development/cjwizard/target/checkout' does not exist
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by creswick** [comment]
Ok, I restored the old repo workspace I was on, deleted the tag, and got through `mvn release:prepare` (after a rollback) without problems, but `mvn release:perform` failed:

```
[INFO] [INFO]
[INFO] [INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ cjwizard ---
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 48.372 s
[INFO] [INFO] Finished at: 2015-04-16T17:04:41-07:00
[INFO] [INFO] Final Memory: 30M/448M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project cjwizard: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]
[INFO] [ERROR]
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR]
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 53.225 s
[INFO] Finished at: 2015-04-16T17:04:41-07:00
[INFO] Final Memory: 13M/310M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.3.2:perform (default-cli) on project cjwizard: Maven execution failed, exit code: '1' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by creswick** [comment]
Ok, I *think* I did a snapshot deployment with `mvn clean deploy`, but I'm out of time today.  I'm working through this document still: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by guerda** [comment]
I'm not sure that you have to specify the developerConnection via -DconnectionUrl= because it should be defined correctly in the pom.xml.
Did you call mvn release:perform without any arguments?

**Comment by creswick** [comment]
> Did you call mvn release:perform without any arguments?

I did -- this is the error I see:

'''
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project cjwizard: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]
'''

**Comment by creswick** [comment]
@guerda @PhoneixS I think one of you folks should take this over fully, so I'm not a bottle neck anymore. I can make one / both of you admins for the github organization -- is there anything else I need to do so that you can handle the maven integration and etc..?

**Comment by PhoneixS** [comment]
I'm too busy in the work now but I can try it in June. Anyway I think that @guerda has more experience with this than me (that I have 0 experience with maven), so he should take it (if he want to).

**Comment by guerda** [comment]
I will try and look into it. I cannot say anything definitely yet. I will try :)

**Comment by Petikoch** [comment]
Hello @guerda and @PhoneixS ,

CJWizard is now deployed to "Bintray JCenter" (https://bintray.com/bintray/jcenter), an alternative for "maven central". See also https://github.com/cjwizard/cjwizard/issues/14.

It's located here: https://bintray.com/cjwizard/CJWizard/cjwizard

Do you insist to have it also in "maven central"?

Otherwise we could close this "old" issue.

Best regards,
Peti

**Comment by PhoneixS** [comment]
Yes I think it's enough.

El lun, 14 de noviembre de 2016 21:21, Peti Koch <notifications@github.com>
escribió:

Hello @guerda <https://github.com/guerda> and @PhoneixS
<https://github.com/PhoneixS> ,

CJWizard is now deployed to "Bintray JCenter" (
https://bintray.com/bintray/jcenter), an alternative for "maven central".
See also #14 <https://github.com/cjwizard/cjwizard/issues/14>.

It's located here: https://bintray.com/cjwizard/CJWizard/cjwizard

Do you insist to have it also in "maven central"?

Otherwise we could close this "old" issue.

Best regards,
Peti

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cjwizard/cjwizard/issues/35#issuecomment-260450925>,
or mute
the thread
