### ISSUE TITLE
Create sample project for testing and demonstrations.

### ISSUE THREAD

**Issue by creswick** [cjwizard/cjwizard#39]
Issue #38 revealed how bad our current testing is.  One thing we could do to help is to build a minimal sample project (adapting the quickstart?) and put it in the repo (perhaps in a `samples` directory).

Ideally, that would be built and run, using the latest version in target, before each deploy.  I expect that that will require some interesting scripting / maven magic to happen in a nice seamless way, but even if it's manual that'd be a start.

If anyone has a simple sample that they'd be willing to share, please let me know!

**Comment by stevesobol** [comment]
Closing this issue, as the forthcoming (as in, "I'm creating it now") 1.0.9 release is split into two different projects (thanks, @spyhunter99)
