### ISSUE TITLE
WizardPage._controller is private

### ISSUE THREAD

**Issue by creswick** [cjwizard/cjwizard#4]
_From [Kissa...@gmail.com](https://code.google.com/u/106643232835441602005/) on January 11, 2011 16:37:09_

I can not programmatically move to the next page. Why is _controller private, and not protected in WizardPage?
Being protected it would allow further accessing the controller functions from a wizard page (inheriting WizardPage).

_Original issue: http://code.google.com/p/cjwizard/issues/detail?id=4_

**Comment by Petikoch** [comment]
Closed because no updates on this issue since 2014. Please reopen if necessary.
