### ISSUE TITLE
Proposoal of "better" values for cjwizard_de.properties

### ISSUE THREAD

**Issue by Petikoch** [cjwizard/cjwizard#40]
Current values:

    PREVIOUS=Zuruck
    NEXT=Nachste
    FINISH=Fertig
    CANCEL=Cancel

"Better" values:

    PREVIOUS=< Zurück
    NEXT=Weiter >
    FINISH=Fertig
    CANCEL=Abbrechen

Best regards,
Peti

**Comment by Petikoch** [comment]
@creswick , would you like a pull request for this?

**Comment by creswick** [comment]
@Petikoch a PR would be great, but I can also port them easily.  I'm just waiting to get feedback from another German speaker.

**Comment by Petikoch** [comment]
@creswick , do you know someone who speaks german? 
Would you like me to ask someone like german speaking Java Champion @lukaseder for a second opinion? 

:-)

Best regards,
Peti

**Comment by lukaseder** [comment]
Sure, I can help you do your translation work. My hourly rate is ... ;)

Anyway, yeah, it's an improvement, although, I'm never a big fan if UI design (e.g. `>` and `<`) goes into translations... that's up to you

**Comment by creswick** [comment]
@lukaseder Thanks! Two other German speakers also concur :). I may be able to fold these changes in today.

I agree about the < > characters, and there was no real good reason for them to be there (other than expediency).

They should probably be computed based on locale settings so they work for languages that don't follow wester reading order; if anyone wants to take a stab at that...

**Comment by creswick** [comment]
Fixed by commit a95861c

**Comment by Petikoch** [comment]
Excellent! 👍 

What about releasing the latest changes? I'd pull it on Monday and "put it in production"... 

Best regards,
Peti

**Comment by creswick** [comment]
1.0.7 should be released - it has the slf4j changes, too. (ugh, that probably should have been a 1.1 release...)
