### ISSUE TITLE
Encoding issue with i18n ResourceBundle values (1.0.7)

### ISSUE THREAD

**Issue by Petikoch** [cjwizard/cjwizard#41]
Good morning @creswick,

the german `< Zurück` (English: `< Prev`) shows up as `< ZurÃ¼ck` in my application.

I _guess_ this is because the properties files are stored using UTF-8 (dev-time) and read using ISO-8859-1 (runtime), like described in http://stackoverflow.com/q/4659929/1662412. 

Best regards,
Peti

**Comment by Petikoch** [comment]
The simplest fix would be to just store the .properties files using ISO-8859-1.

**Comment by creswick** [comment]
Dang... I need to set up a sample app so I can test things better before
release.

I'm actually without a dev machine for a while, so this will be tricky to
fix and release quickly.

**Comment by creswick** [comment]
I went ahead and merged the PR, but I don't yet have an environment set up to do deployments.

**Comment by Petikoch** [comment]
Release it anyway? Pragmatic approach...

**Comment by creswick** [comment]
@Petikoch can you take over releases? I just don't have time to even get an environment up again, and cut releases in a reasonable timeframe. I'm happy to do whatever I need to enable someone else to take over.

If you can't either, we need to find someone who can.

**Comment by Petikoch** [comment]
@creswick I can help. If you add me as "collaborator" to the project, I can do the maintenance. Would you like me to "care for everything" (issues, pull requests, ...) or just for the releases? 

Best regards from Switzerland,
Peti

**Comment by creswick** [comment]
@Petikoch thanks! I've added you to the team, and you should have full access to all the github things.  I'd be happy to transition all the maintainer duties / responsibilities / glory ;)

**Comment by Petikoch** [comment]
@creswick It works like a charm... :-) However... In order to publish a release to JCenter I need some help. I didn't use Maven the last couple of years, I switched over to gradle. 

How did you do the releases?
- a local "maven deploy"?
- what local files do I need the setup? for the gpg signing?

PS: I'd like to keep the maven build for the moment

**Comment by creswick** [comment]
'maven deploy' should do it, but your specific deployment details will
differ; I can't share the keys I used, so we'll need to change to a new
keypair.

**Comment by Petikoch** [comment]
@creswick, I set up an cjwizard organisation in Bintray and invited you to join it. After the join you can "move" the creswick/cjwizard repo to the cjwizard organisation (https://bintray.com/docs/usermanual/interacting/interacting_transferringownershipofarepoyouowntoanorganization.html). 

Regarding gpg signing... no big deal. We enable "signing by bintray on upload" in the cjwizard organisation  and bintray will sign the cjwizard artifacts automatically with the bintray key.

What do you think?

Best regards,
Peti

**Comment by creswick** [comment]
That sounds great!

The documentation you linked to doesn't seem to be up-to-date with the
bintray UI, so I've emailed support to get help on transitioning the repo.

Thanks!
--Rogan

**Comment by Petikoch** [comment]
Probably it was because the "cjwizard bintray organisation" didn't have a repository... 

I just created a "maven" repository in bintray: https://bintray.com/cjwizard/Maven

Would you like to be the owner of the "cjwizard bintray organisation"? At the moment you are "admin" and the "owner" is me. https://bintray.com/cjwizard/organization/edit

Best regards!
Peti

**Comment by creswick** [comment]
ah, that was it! It should be transferred to the organization now.

I think you should be the owner, unless you really don't want to be.

Thanks!

**Comment by Petikoch** [comment]
Fixed with https://github.com/cjwizard/cjwizard/releases/tag/cjwizard-1.0.8
