### ISSUE TITLE
Broken link to cjwizard1.png in README.md 

### ISSUE THREAD

**Issue by Petikoch** [cjwizard/cjwizard#44]
@creswick , in the README.md is http://cjwizard.googlecode.com/files/cjwizard1.png referenced. 

However, that file doesn't exist any more (googlecode is gone). Do you have it somewhere?

Best regards,
Peti

**Comment by creswick** [comment]
I don't have it, unless it's somewhere in the repo.

**Comment by Petikoch** [comment]
There is none in the repo. I'll create a new one...

**Comment by Petikoch** [comment]
I found a tiny preview in "google image search" and added it to the repo

**Comment by Petikoch** [comment]
Finally found the real png in 
https://web.archive.org/web/20141224154218/https://code.google.com/p/cjwizard/
