### ISSUE TITLE
Example for more complex workflows?

### ISSUE THREAD

**Issue by spyhunter99** [cjwizard/cjwizard#48]
Is there any example for optional steps, or tree like structures

For instance, if option A is check, the slide page should page A1, otherwise skip to page B

**Comment by pablopasten** [comment]
Is there any way to press next and go to any page or last page directly? with out going step by step. I need made a more complex flow

**Comment by stevesobol** [comment]
It looks like I need to create some. This goes hand-in-hand with the issue I opened for documentation.

I'd like to try to cook up something this coming week. No promises - it depends on how heavy my workload is - but this is on my radar.

Best
--Fearless Leader.

**Comment by spyhunter99** [comment]
I think I need something like this.

![untitled diagram 2](https://user-images.githubusercontent.com/1975321/36519525-00607e02-175a-11e8-9fbc-f4f492ddfb19.png)

**Comment by spyhunter99** [comment]
ok so injecting a new page via

````
new WizardPage("Three", "Third Page") {
                {
                    add(new JLabel("Three!"));
                    setBackground(Color.green);
                }
  
                /**
                 * here we are dynamically injecting a new page into the workflow
                 * @param path
                 * @param settings 
                 */
                public void rendering(List<WizardPage> path, WizardSettings settings) {
                    super.rendering(path, settings);
                    getController().getPath().add(new WizardPage("Step 3A", "injected") {
                        {
                            add(new JLabel("3A!"));
                            setBackground(Color.BLUE);
                        }
                    });
                    
                }
            }
````

is definitely not right

**Comment by spyhunter99** [comment]
and ` getController().visitPage(pages[0]);` doesn't appear to be right either, throws the following
````
Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException
	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:280)
	at java.util.ArrayDeque.pop(ArrayDeque.java:517)
	at com.github.cjwizard.WizardContainer.visitPage(WizardContainer.java:488)
````

**Comment by spyhunter99** [comment]
![untitled diagram 3](https://user-images.githubusercontent.com/1975321/36624885-6e74f636-18e3-11e8-8f87-414f4e792d4b.png)

slightly revised setup that's a bit more complex

**Comment by stevesobol** [comment]
I am SO sorry for the delay. Real life and work intervened.

I only have a little time today, but I am using that time to check out the existing code and see how it's generating the history (which, based on my earlier observations, is where the problem occurs). I would like to try to come up with a fix sometime before the end of the month.

**Comment by stevesobol** [comment]
Either today or tomorrow, I am going to figure out what's going on. I actually printed out the source to `WizardContainer.visitPage()` to see what's happening. Stay tuned.

**Comment by stevesobol** [comment]
I'm beat. But I have some free time tonight, so I'm trying to analyze how `WizardContainer` works. `next()` and `prev()` work perfectly. `visitPage()` is broken. So I need to figure out where the differences are.

**Comment by spyhunter99** [comment]
looked at this again. visitPage kind of works. I am brought to the right page, however the next button doesn't seem to be tracking correctly. So if i'm on 3, i can jump right to 5, but the next button (first click) stays at 5, next again goes to 6. Previous works perfectly though. I narrowed it down to the demo's implementation of `PageFactory#createPage`. After a fancier implementation it seems to be working well now. I'll clean up it and PR tonight
