### ISSUE TITLE
No Taskbar item

### ISSUE THREAD

**Issue by creswick** [cjwizard/cjwizard#5]
_From [Kissa...@gmail.com](https://code.google.com/u/106643232835441602005/) on February 17, 2011 03:12:39_

By default the wizard does not add a taskbar item.
It should though IMO.
At least there should be an option to do so.

_Original issue: http://code.google.com/p/cjwizard/issues/detail?id=5_

**Comment by stevesobol** [comment]
I'm wondering why a taskbar item would be needed, since (presumably) the program displaying the wizard would have its own taskbar button. I'm also not sure this is a bug.
