### ISSUE TITLE
Who would like / will maintain the cjwizard project?

### ISSUE THREAD

**Issue by Petikoch** [cjwizard/cjwizard#54]
Hi everybody, 

recently, there were a couple of issues and pull requests from @spyhunter99... 

@stevesobol mentioned, that he took over the project from @creswick (https://github.com/cjwizard/cjwizard/issues/49).

That's good news for cjwizard :-)

Technically, I supported the project last year a little bit (https://github.com/cjwizard/cjwizard/releases) and helped to make it available via Bintray (https://bintray.com/cjwizard). I have also the necessary "permissions" for managing the organization in Github as well as in Bintray.

Personally, I don't use cjwizard at the moment, so I'm not that much interested in it right now. 

Enough of the introduction... 

-> Who would like to maintain the project?

I could help with the transition... 

Best regards,
Peti

**Comment by stevesobol** [comment]
That'll be me. Let's do this thing!

**Comment by stevesobol** [comment]
Do you use the Bintray credentials for other projects, or do you use them exclusively for cjwizard?

If you only use them for cjwizard, you can put them in a kdbx file using Keepass, or I can give you my PGP public key and you can email them to me.

**Comment by Petikoch** [comment]
@creswick, could you briefly confirm @stevesobol  as the new project leader? I'll add him afterwards to the Github organization and the Bintray organization. 

@stevesobol, as soon as you are a member in the Bintray organization, you'll get the key from there. You'll have to add it in your local maven settings.xml in order to be able to deploy new cjwizard binary versions.
To speed things up: 1) make sure you have a Bintray account (I'd recommend the "login using Github account" way) and 2) make sure you have a local maven 3.x installation.

Best regards,
Peti

**Comment by creswick** [comment]
I'm happy to have @stevesobol take over, but I honestly don't know any of you folks that well, so I don't have strong feelings about who takes charge.  It's great to see folks interested in the project, and I'm thrilled to see it in use!

My primary concerns are:
 (1) The project stays alive, as long as it is useful, and as long as we can keep it that way, and 
 (2) Everyone who wants to contribute has an opportunity

I'm hoping to lurk for a while, and if a gitter / slack channel gets going I'll probably hang out there, but I don't expect I'll need the library my self, and I won't have time to make any technical contributions.

Let me know if / how I can help with things.

**Comment by Petikoch** [comment]
@stevesobol, I just invited you as a member of the cjwizard github organization. With this, you have "full rights" to the repo and as well to the github organization itself.

Let me know when you are ready with the Bintray user account... 

And let me know, when I can help with something! :-)

**Comment by stevesobol** [comment]
I am on Bintray now, signed in with my Github credentials https://bintray.com/lobosstudios

@creswick may or may not recall our email conversations where I repeatedly apologized for not having enough time to work on the project. That ends this week. (Seriously.) I want to move forward with whatever bugfixes and enhancements are on the table first, and then we can figure out where we want to go from there. 

One thing I've been thinking about is maybe adapting the library to work with Swing *or* JavaFX. Maybe we could discuss that later.

I'm going to need some guidance at first.

**Comment by creswick** [comment]
@stevesobol I definitely remember! I'd assumed you were just busy with other things.  It's great that you're able to work on the project now!

**Comment by stevesobol** [comment]
Thanks. Bintray says "29 days left in trial." It's still free for OSS, right? :)

I approved the invite.

CI is one area where I'll need to get up to speed. I've used TeamCity in the past, and I plan on using it for my own personal projects (I'm a current JetBrains customer and big fan of the company's products) -- but I've never used Travis CI. I'll be fine, just may need a little bit of hand-holding early on.

**Comment by stevesobol** [comment]
*facepalm* @Petikoch you may need to re-send that invite. I looked, and I'm on a trial of Bintray **ENTERPRISE.** I need to cancel that trial, but my organization will be deleted (which is fine with me). 

Bear with me for a moment...

... OK. I cancelled, and my organization was deleted, but my **account** is still active and I'm still showing that I'm part of the _cjwizard_ org. Thank $DEITY.

**Comment by spyhunter99** [comment]
I have a sonatype account and can help setup maven to publish to there. it's definitely free

**Comment by stevesobol** [comment]
Thanks. 

I have created https://cjwizard-devs.slack.com but didn't invite anyone yet. I did install the github and Travis CI apps in #general.

**Comment by Petikoch** [comment]
@stevesobol

- probably you can "downgrade" your bintray account to the OSS one? 
- signup for the free OSS account would have been via https://bintray.com/signup/oss
- https://bintray.com/stevesobol is now "admin" member of https://bintray.com/cjwizard

@spyhunter99 

- sure, you and @stevesobol can switch over to sonatype, if you want
- personally, I find bintray easier to use than sonatype
- and: bintray is already setup for cjwizard and ready to use

@stevesobol 

I propose the following next steps
1. work on the source: pull requests / issues 
2. setup a "developer page" with a "how to communicate (issues, slack, ...)", a "how to release", "details about the CI-server", ...
3. as soon as the source for next version is ready, get started with publishing to bintray or whatever
4. ...

Best regards,
Peti

**Comment by stevesobol** [comment]
- https://cjwizard-devs.slack.com/ (I'll need to invite people to the channel)
- Let's continue to use bintray. I can handle learning how to use it...
- @Petikoch that sounds like the way forward... excellent... Will you continue to be involved?

**Comment by Petikoch** [comment]
@stevesobol, my further involvement?

As mentioned, I'm not an active user of cjwizard anymore. But I'll be glad to help you getting started.

What is your motivation @stevesobol for the involvement in cjwizard?

**Comment by stevesobol** [comment]
@Petikoch Ah... ok, I had to go re-read the first message in the thread. Yes, the help will be very deeply appreciated. Once I've familiarized myself with the project, I will be fine.

My motivation:
- My first real use of open-source software was Red Hat Linux 4.1 at my first-ever IT job, back in late 1995. I've been a fan of OSS and an OSS user ever since then, and I keep on promising myself that I'll give back to the community. This is a way to do that.
- I like what I initially saw in cjwizard, and I want to keep the project going.

**Comment by stevesobol** [comment]
Do we need to keep this bug open? Does anyone have any objections to me taking over the project?

**Comment by PhoneixS** [comment]
No, I think you can go ahead.

**Comment by stevesobol** [comment]
I just released 1.0.9 on Github but I'm getting 401 Unauthorized when deploying to Bintray. Help please :(

**Comment by stevesobol** [comment]
I'm having trouble navigating around Bintray. I'm an admin, I should be able to set my own permissions to allow API access, but...

Also, if you're not working on the project anymore, can you make me owner of the cjwizard org on Bintray? Thanks.

**Comment by creswick** [comment]
Peti Koch is the current owner of that org; (https://bintray.com/petikoch)
It looks like I can probably switch that to you, but I'd like to make sure
he knows what's going on first.

**Comment by stevesobol** [comment]
> Peti Koch is the current owner of that org

Yes. The request was actually directed at him :) 

Since he is not an active developer, I expect that it might take him a day or two to respond. That's fine.

**Comment by Petikoch** [comment]
@stevesobol , you are now the "owner" of the cjwizard organization in bintray (https://bintray.com/cjwizard/organization/edit). Before, you were "admin".

**Comment by Petikoch** [comment]
@stevesobol, regarding your 401 Bintray upload issue... 

How does your maven settings.xml look like? (see also https://github.com/cjwizard/cjwizard/issues/54#issuecomment-289542343) 

My settings.xml looks like this
```
...
	<servers>
		<server>
			<id>bintray-cjwizard-CJWizard</id>
			<username>petikoch</username>
            <password>...secret...</password>
        </server>
	</servers>
	
    <profiles>
        <profile>
            <repositories>
                <repository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>bintray-cjwizard-CJWizard</id>
                    <name>bintray</name>
                    <url>http://dl.bintray.com/cjwizard/CJWizard</url>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>bintray-cjwizard-CJWizard</id>
                    <name>bintray-plugins</name>
                    <url>http://dl.bintray.com/cjwizard/CJWizard</url>
                </pluginRepository>
            </pluginRepositories>
            <id>bintray</id>
        </profile>
    </profiles>
	
    <activeProfiles>
        <activeProfile>bintray</activeProfile>
    </activeProfiles>

...
```

For more details see also https://bintray.com/docs/usermanual/formats/formats_mavenrepositories.html#anchorMavenDepoy

**Comment by stevesobol** [comment]
Mine didn't. I didn't realize that Bintray can generate the settings.xml, so I generated it, and now it looks like yours but I'm still seeing HTTP 401s. Will continue to work on this.

**Comment by stevesobol** [comment]
Ooh. Had to set <server> / <id> properly. It worked. Now I need to upload the demos. Thanks for the help

**Comment by spyhunter99** [comment]
Use the maven release plugin next time

**Comment by stevesobol** [comment]
So.... It's... significantly later than I'd hoped, but I'm actually devoting time to the project now, starting with the documentation. The "website" I have online at cjwizard.com is really just a landing page. I'm working on an _actual_ website now, and actual docs. 

RIP Bintray, and I don't want to screw around with Maven Central, so I am going to self-host. I'm running Sonatype Nexus OSS, and I've set up a Maven repository; there's nothing there yet, but you can browse the (currently empty) repo [here.](https://repos.lobosstudios.com/#browse/browse:java-dev)

Better late than never. I'm pleased to finally be able to put real work into this project, instead of just approving and merging the occasional pull request.

**Comment by creswick** [comment]
Thanks for the update, I'm glad to hear you're working on it!
