### ISSUE TITLE
WizardPage advance to next?

### ISSUE THREAD

**Issue by spyhunter99** [cjwizard/cjwizard#55]
From the context of a wizard page, is there a way to advanced to the next wizard page?

**Comment by creswick** [comment]
I don't think there's a good way to do that.

I believe you need a reference to the WizardController (the WizardContainer is an instance of this), but it's not exactly easy to pass that into your WizardPages.  It could probably be exposed, though.

**Comment by spyhunter99** [comment]
K guess I know what I'm doing this weekend

**Comment by stevesobol** [comment]
@spyhunter99 Just merged your pull request.
