### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by stevesobol** [cjwizard/cjwizard#57]
We need more complete documentation, including more sample code.

**Comment by spyhunter99** [comment]
consider moving the "docs" folder into /src/site/markdown and adding the site descriptor. Then you can build a neato website using `mvn site` and push it to gh-pages

**Comment by stevesobol** [comment]
I think that makes sense, at least for the docs. I'm going to put a full website up at cjwizard.com, and we can link to the docs here.

**Comment by stevesobol** [comment]
Alright, I generated the site. We can only choose between master and gh-pages so I'll create a gh-pages branch and put the site there

**Comment by stevesobol** [comment]
The generated documentation needs to be in /docs for Github to properly pick it up. So, it'll be in /docs in the gh-pages branch. It won't be updated automatically but that's fine for now

**Comment by spyhunter99** [comment]
oh that's right, they changed it. in my other projects, i made a separate git repo and pushed the maven generated site to it. But on other projects, a divorced branch in the same repo works. 
![image](https://user-images.githubusercontent.com/1975321/51802807-7aba4580-221b-11e9-9661-1d4d084764b2.png)
