### ISSUE TITLE
Scrolling the in the Wizard Panel?

### ISSUE THREAD

**Issue by spyhunter99** [cjwizard/cjwizard#58]
I've ran into an issue where I have a Panel that extends WizardPanel that is too tall for displaying on the screen. I'm not a swing expert and i'm not too sure how to proceed. I was thinking i wrap my panel in a scroll view but i'm not sure if there's an easier solution that could be incorporated into the library. Thoughts on this?

**Comment by stevesobol** [comment]
I'm not sure either. Can you provide a code sample?

**Comment by spyhunter99** [comment]
ahh found the solution (netbeans centric)

Create a new JPanel
Add a scroll view that fills the panel
Drag a new panel into the scroll view
Right click the new inner pannel, then design this.
build your layout as normal, then it's scrollable within the wizard

**Comment by stevesobol** [comment]
Matisse generates standard Java code, so even though you may have used Matisse, your solution is usable in other IDEs as well. I think once we fork off the demo from the main library, we should add a sample that does exactly what you're talking about.
