### ISSUE TITLE
Feature request, on before next and on before previous actions

### ISSUE THREAD

**Issue by spyhunter99** [cjwizard/cjwizard#61]
Not sure if this exists already but it would be super useful to trap the events for next and previous and the ability to cancel said action.

use case
user clicks next
app prompts "are you sure you want to do that" yes/no jdialog

**Comment by stevesobol** [comment]
Great idea. I’m digging into cjwizard this coming week and would like to get this implemented then. I’m reviewing that pull request this weekend, btw (to refactor the samples out into a separate Maven project)

 

--

Lobos Studios | Phone: 877.919.4WEB | LobosStudios.com | Facebook.com/LobosStudios | @LobosStudios

Web Development - Mobile Development - Helpdesk/Tech Support - Computer Sales & Service

Acer Authorized Reseller - Computers, Windows and Android Tablets, Accessories

 

Steve Sobol - CEO, Senior Developer and Server Jockey

steve@LobosStudios.com

**Comment by spyhunter99** [comment]
turns out, it does exist. override onNext, then return false if there was some kind of issue
