### ISSUE TITLE
README.md: dev.java.net not available any more

### ISSUE THREAD

**Issue by janmaterne** [cjwizard/cjwizard#64]
The main page lists the >>Java Wizard library at Java.net (https://wizard.dev.java.net/).<<, but that page is not available any more.

**Comment by creswick** [comment]
I made a small change to the readme in 00da50766532566b086c9f6719e9a1d158bd6d00

**Comment by creswick** [comment]
@janmaterne thanks for letting us know!

**Comment by stevesobol** [comment]
Thanks @creswick. I need to overhaul the readme anyhow, but that will work for now. Is there any way for me to get notifications anytime someone opens a bug? I've checked my notification settings but I'm not sure there is. I could have taken care of this.

**Comment by creswick** [comment]
@stevesobol I do get emails for every new issue; I'm not sure I get notifications for comments that don't mention me directly.

I *think* the notifications I get are just because I'm 'watching' this repo, but I'm not certain if there is another setting I've toggled elsewhere.
