### ISSUE TITLE
New Slack channel

### ISSUE THREAD

**Issue by stevesobol** [cjwizard/cjwizard#68]
@PhoneixS @mperrando @spyhunter99 

We have a new Slack channel available at **[cjwizard-users.slack.com](https://cjwizard-users.slack.com).**

**Comment by stevesobol** [comment]
I tagged you guys because I want you to join, btw. Please join. :)

**Comment by PhoneixS** [comment]
It says that if I don't have an account the admin must send me an invitation, maybe you should send invitations ;-)

**Comment by stevesobol** [comment]
Well - apparently there is no way to create a public channel. Not cool, since I liked the previous URL and it is now unavailable after I deleted the old channel.

**Comment by stevesobol** [comment]
I should have said public WORKSPACE.

Yeah, I'm going to need to invite everyone. If you don't want your email address exposed here, let me know and I'll delete it as soon as I send you the invite.

**Comment by spyhunter99** [comment]
same id at gmail

**Comment by stevesobol** [comment]
URL updated to the new one that I shouldn't have had to create
