### ISSUE TITLE
Add support for Java 9 and 10

### ISSUE THREAD

**Issue by stevesobol** [cjwizard/cjwizard#69]
We need to make sure we are supporting Java 9 and 10. Oracle has 10.0.1 out now, and it can be downloaded using [this link](http://www.oracle.com/technetwork/java/javase/downloads/index.html), while the OpenJDK 10.0.1 download can be found [here](http://jdk.java.net/10/).

It may be as simple as adding the proper keywords to `travis.yml` and letting Travis successfully build the project. Actually, it SHOULD be that simple. We are constrained, at the moment, by the fact that [Travis CI support for Java 10 isn't quite ready for prime-time](https://github.com/travis-ci/travis-ci/issues/9368). And I've had no specific requests to support 9 OR 10 yet, so I'm going to hold off on making any changes for now. But hopefully we'll be able to get this done soon

**Comment by stevesobol** [comment]
I actually may have some time over the next week or two. This is a priority now that I can actually work on this project.

**Comment by spyhunter99** [comment]
The open pull request added travis build targets for jre9, 10 and 11, all of them passed the build with minor javadoc changes.

**Comment by stevesobol** [comment]
You missed a couple entries. :)

I'm adding them now.

**Comment by stevesobol** [comment]
Done
