### ISSUE TITLE
Maven dependency snippet doesn't work

### ISSUE THREAD

**Issue by shannah** [cjwizard/cjwizard#71]
The maven dependency snippet in the readme doesn't seem to work for me.

~~~
<dependency>
  <groupId>com.github.cjwizard</groupId>
  <artifactId>cjwizard</artifactId>
  <version>x.y.z</version>
  <type>pom</type>
</dependency>
~~~

The snippet matches the snippet that is provided in the [bintray link](https://bintray.com/cjwizard/CJWizard/cjwizard)

In order for my project to actually download the classes, I needed to remove the `<type>pom</type>` tag.  After that the jars were downloaded correctly and I was able to use the classes.

**Comment by spyhunter99** [comment]
`<dependency>
  <artifactId>cjwizard</artifactId>
  <version>1.0.9</version>
</dependency>
`
