### ISSUE TITLE
Demo's are broken

### ISSUE THREAD

**Issue by spyhunter99** [cjwizard/cjwizard#75]
Not sure what happened but all 3 demo's start up, then exit immediately after pressing the next button.

**Comment by spyhunter99** [comment]
ahh the problem was introduced with PR https://github.com/cjwizard/cjwizard/pull/67
onPageChanging calls this.dispose() which kills the panel

**Comment by stevesobol** [comment]
Since this is fixed, and you closed a related issue, I'm going to close this one.
