### ISSUE TITLE
Broken link in QuickStart guide

### ISSUE THREAD

**Issue by vicnevicne** [cjwizard/cjwizard#83]
The introduction of the page at https://github.com/cjwizard/cjwizard/blob/master/src/site/markdown/quickstart.md
contains a link to 
https://github.com/cjwizard/cjwizard/blob/master/src/site/src/main/java/com/github/cjwizard/WizardTest.java
which is 404.
I guess it should be changed to 
https://github.com/cjwizard/cjwizard/blob/master/cjwizard-demo/src/main/java/com/github/cjwizard/demo/WizardTest.java
Thanks for the nice project btw :-)

**Comment by stevesobol** [comment]
Just briefly checked the source, and yes, it's `com.github.cjwizard.demo.WizardTest`. Please hold :)

**Comment by stevesobol** [comment]
Pull request https://github.com/cjwizard/cjwizard/pull/84

**Comment by stevesobol** [comment]
Fixed; thank you for the report. I'm finally at the point where I can put in a decent amount of time on this project. Please open an issue (issues??) if you have feature requests.
