### ISSUE TITLE
Where to move Maven repo?

### ISSUE THREAD

**Issue by stevesobol** [cjwizard/cjwizard#86]
JCenter is going away as of May 1st, 2021.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/#:~:text=JFrog%20is%20evolving%20to%20meet%20the%20new%20challenges%20that%20developers%20face.&text=To%20streamline%20the%20productivity%20of,services%20on%20May%201st%2C%202021.

So, the question is, do we move to:

- A free JFrog Artifactory account? (Artifactory has a free tier, https://jfrog.com/pricing/)
- Maven Central? I'd have to check whether we're mirroring to Maven Central or not.
- Nexus? I have a Sonatype Nexus OSS server running at https://repos.lobosstudios.com. It's currently only hosting one private Debian APT repo right now, but my plan's always been to host public repos. I've just had nothing to host up until now.

**Comment by spyhunter99** [comment]
my vote is central via oss.sonatype.org. I can definitely publish to there. Getting access is easy, just need a jira ticket. I can have the pom setup for set up for publishing to there pretty quickly

**Comment by stevesobol** [comment]
Works for me. Is there a place where I can sign up? I can't find one, and I'd like both of us to be able to submit new releases to the repo.

Googling "nexus oss" gives me search results the Open-Source version of Nexus -- as in, the OSS-licensed version of the on-premise software (which isn't what I'm looking for).

**Comment by spyhunter99** [comment]
this is the how to.
https://central.sonatype.org/pages/ossrh-guide.html

jira link
https://issues.sonatype.org/secure/Dashboard.jspa

should be a create account link there.

**Comment by stevesobol** [comment]
Ah! Ok. Yeah, let's pull the trigger. I'll update the website. We should probably update the README as well. I'll do that too.

Please request access for yourself and for stevesobol-sonatype. I already have a Sonatype Jira account. :)

Thanks (again) :)
