### ISSUE TITLE
Can't download cjwizard.jar

### ISSUE THREAD

**Issue by otrebski** [cjwizard/cjwizard#89]
There was a sun set of Bintray https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
Gradle can't download dependencies from https://bintray.com/cjwizard/CJWizard/cjwizard.
 Can you upload dependencies to other maven repository?

**Comment by stevesobol** [comment]
Yes, I'm aware that Bintray closed up shop. I have a Sonatype Nexus OSS server running, and one of the reasons I set it up (probably THE reason) is so I could host my own repos, including a Maven repo. I have a Maven repo in place, but it's empty at the moment, but within the next day or two, I will build 1.0.9 (the latest release) and publish it. 

This is one of the things that has been on my to-do list for a while, but paying work has gotten in the way.

**Comment by stevesobol** [comment]
I have the artifacts deploying to my Nexus server now. I am waiting for LGTM to complete a security analysis so I can approve and merge the pull request.

I didn't change any of the code, but I'm bumping the version to 1.0.9.1 anyhow. A release will be made available shortly, on Github.

**Comment by stevesobol** [comment]
All set! https://github.com/cjwizard/cjwizard/releases/tag/cjwizard-1.0.9.1

The Readme has been updated, and will tell you how to grab artifacts from the new repo.

I'll close this issue once you reply and confirm that you can get 1.0.9.1.

Thank you for giving me the push I needed to get this done. This has been on my to-do list forever.

**Comment by stevesobol** [comment]
I'm assuming everything's good... I'm closing this issue.
