### ISSUE TITLE
Access to Buttons in WizardContainer would be useful

### ISSUE THREAD

**Issue by creswick** [cjwizard/cjwizard#9]
_From [cscha...@gmail.com](https://code.google.com/u/117318641114575472364/) on June 16, 2011 17:41:58_

In order to add accelerators and such to the 4 buttons in a WizardContainer (Finish, Cancel, Previous and Next), or to contextually change their text, I had to traverse the Swing container hierarchy and match them by finding JButton's whose actions have the right names. This is less than optimal. 

It would be wondrously useful to have accessors for the buttons, such as getNextButton(), etc. And it wouldn't be very hard.

_Original issue: http://code.google.com/p/cjwizard/issues/detail?id=9_

**Comment by Petikoch** [comment]
Closed because no updates on this issue since 2014. Please reopen if necessary.
